set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4

set mouse=v

syntax on

autocmd FileType html setlocal shiftwidth=4
autocmd FileType sh setlocal shiftwidth=4
autocmd FileType py setlocal shiftwidth=4
autocmd FileType yaml setlocal tabstop=2 shiftwidth=2 softtabstop=2

highlight Comment ctermfg=darkgray

" vim-plug - https://github.com/junegunn/vim-plug
" Specify a directory for plugins
" - For Neovim: ~/.local/share/nvim/plugged
" - Avoid using standard Vim directory names like 'plugin'
call plug#begin('~/.vim/plugged')

" Make sure you use single quotes

Plug 'jamessan/vim-gnupg'
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }
Plug 'junegunn/vim-easy-align'
Plug 'davidhalter/jedi-vim'

" Initialize plugin system
call plug#end()

filetype plugin indent on

" Plugin configuration

" Start interactive EasyAlign in visual mode (e.g. vipga)
xmap ga <Plug>(EasyAlign)

" Start interactive EasyAlign for a motion/text object (e.g. gaip)
nmap ga <Plug>(EasyAlign)

